name: Build master
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: git fetch origin master
          && sudo add-apt-repository -y 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main'
          && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          && sudo apt-get update
          && sudo apt-get install clang-tidy-18
          && sudo apt-get install clang-format-18
          && pip install conan
      - name: Run conan
        run: >
          cd ${{github.workspace}}
          && mkdir build && cd build
          && conan profile detect
          && conan install ..

      - name: Configure CMake
        run: >
          cd ${{github.workspace}}/build
          && cmake .. --preset=conan-release
          -DTIDY=OFF

      - name: Build
        run: >
          cd ${{github.workspace}}/build/Release
          && make

      - name: Static code analysis
        run: > 
          cd ${{github.workspace}}
          && run-clang-tidy-18 -p=build/Release

      - name: Clang-format
        run: >
          cd ${{github.workspace}}
          && find ${{github.workspace}} -name '*.hpp'
          -o -name '*.cpp' -not -path '${{github.workspace}}/build/*'
          | xargs clang-format-18 --Werror --dry-run