name: Build pr
on:
  pull_request:
    types: 
      - edited
      - synchronize
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: git fetch origin master
          && sudo add-apt-repository -y 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main'
          && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          && sudo apt-get update
          && sudo apt-get install clang-tidy-18
          && sudo apt-get install clang-format-18
      - name: Configure CMake
        run: >
          cd ${{github.workspace}}
          && cmake . -B ${{github.workspace}}/build
          -DTIDY=OFF

      - name: Build
        run: >
          cd ${{github.workspace}}/build
          && make

      - name: Static code analysis
        run: > 
          git diff -U0 origin/master
          | clang-tidy-diff-18.py -p1 -path=build

      - name: Clang-format
        run: >
          cd ${{github.workspace}}
          && git diff --name-only --diff-filter=d origin/master
          | grep -i -E '*.(hpp|cpp)'
          | xargs clang-format-18 --Werror --dry-run
