name: Build project
on:
  push:
    branches: 
      - master
  pull_request:
    types: 
      - edited
      - synchronize
    branches:
      - master

jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cd ${{github.workspace}}
          && cmake . -B ${{github.workspace}}/build
          -DTIDY=OFF

      - name: Build
        run: >
          cd ${{github.workspace}}/build
          && make

      - name: Static code analysis
        run: > 
          git diff -U0 master
          | clang-tidy-diff -p1 -path=build

      - name: Clang-format
        uses: akopachov/git-clang-format-diff-action@v1.0.0
        with:
          commit: master # Ref to compare with